'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frm_xml_yarat
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("business_smart.frm_xml_yarat", GetType(frm_xml_yarat).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  {X=615,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property BarManager1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BarManager1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=17,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_baslik_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_baslik.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=732,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_dToplam_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_dToplam.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=123,Y=54} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_fiyattipi_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_fiyattipi.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=17,Y=54} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_hareket_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_hareket.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=243,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_iskonto_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_iskonto.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=348,Y=54} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_Kesinti_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_Kesinti.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=450,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_masraf_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_masraf.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=228,Y=54} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_nGirisCikis_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_nGirisCikis.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=347,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ds_toplam_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ds_toplam.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=114,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property kisayol_hareket_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("kisayol_hareket.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  {X=844,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property OpenFileDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  DevExpress.Utils.ImageCollectionStreamer türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property printlink1_ImageCollection_ImageStream() As DevExpress.Utils.ImageCollectionStreamer
            Get
                Dim obj As Object = ResourceManager.GetObject("printlink1.ImageCollection.ImageStream", resourceCulture)
                Return CType(obj,DevExpress.Utils.ImageCollectionStreamer)
            End Get
        End Property
        
        '''<summary>
        '''  {X=553,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend Shared ReadOnly Property ps_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ps.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
    End Class
End Namespace
