Option Strict Off
Option Explicit On
Imports System.Management
Imports System.Text
Imports System.Collections
Imports System.Threading
Module Langu
    Public Function sArabic(ByVal sOrjinal As String) As String
        Dim sCeviri As String = ""
        If sOrjinal = "StokKodu" Then
            sCeviri = "كود استوك"
        ElseIf sOrjinal = "MalinCinsi" Or sOrjinal = "Stok Adı" Then
            sCeviri = "كود استوك"
        ElseIf sOrjinal = "Tarih" Then
            sCeviri = "تاريخ"
        ElseIf sOrjinal = "StokTipi" Then
            sCeviri = "نوع استوك"
        ElseIf sOrjinal = "Barkod" Then
            sCeviri = "برقود"
        ElseIf sOrjinal = "Birim" Then
            sCeviri = "الوحدة"
        ElseIf sOrjinal = "Miktar" Then
            sCeviri = "العدد"
        ElseIf sOrjinal = "Kdv" Then
            sCeviri = "الضرائب"
        ElseIf sOrjinal = "Isk1" Then
            sCeviri = "خصم 1"
        ElseIf sOrjinal = "Isk2" Then
            sCeviri = "خصم 2"
        ElseIf sOrjinal = "Isk3" Then
            sCeviri = "خصم 3"
        ElseIf sOrjinal = "Isk4" Then
            sCeviri = "خصم 4"
        ElseIf sOrjinal = "Fiyat" Then
            sCeviri = "السعر"
        ElseIf sOrjinal = "BirimFiyat" Then
            sCeviri = "سعر الوحدة"
        ElseIf sOrjinal = "Tutar" Then
            sCeviri = "مجموعة"
        ElseIf sOrjinal = "DovizFiyati" Then
            sCeviri = "سعر العملة الاجنبية"
        ElseIf sOrjinal = "DovizTutari" Then
            sCeviri = "اجمالي العملة"
        ElseIf sOrjinal = "DepoKodu" Then
            sCeviri = "مستودع"
        ElseIf sOrjinal = "Personel" Or sOrjinal = "Satıcı" Then
            sCeviri = "الموظفين"
        ElseIf sOrjinal = "GercekToplam" Then
            sCeviri = "جملة الفعلي"
        ElseIf sOrjinal = "KayitNo" Then
            sCeviri = "رقم القيد"
        ElseIf sOrjinal = "StokNo" Then
            sCeviri = "رقم استوك"
        ElseIf sOrjinal = "BirimNo" Then
            sCeviri = "رقم الوحدة"
        ElseIf sOrjinal = "Iskonto" Then
            sCeviri = "مبلغ الخصم"
        ElseIf sOrjinal = "AlisFiyati" Then
            sCeviri = "شراء"
        ElseIf sOrjinal = "Maliyet" Then
            sCeviri = "التكلفة"
        ElseIf sOrjinal = "Prim" Or sOrjinal = "Prim%" Then
            sCeviri = "ترغيب"
        ElseIf sOrjinal = "Opsiyon" Then
            sCeviri = "أختيار"
        ElseIf sOrjinal = "DovizCinsi" Then
            sCeviri = "نوع العملة"
        ElseIf sOrjinal = "Pb" Then
            sCeviri = "نوع العملة"
        ElseIf sOrjinal = "Kur" Then
            sCeviri = "نسبة العملة"
        ElseIf sOrjinal = "Masraf" Then
            sCeviri = "مصاريف"
        ElseIf sOrjinal = "Aciklama" Then
            sCeviri = "بيانات"
        ElseIf sOrjinal = "FiyatAciklama" Then
            sCeviri = "بيان السعر"
        ElseIf sOrjinal = "Status" Then
            sCeviri = "الدرجة"
        ElseIf sOrjinal = "BirimMiktar" Then
            sCeviri = "عدد الوحدة"
        ElseIf sOrjinal = "Termin" Then
            sCeviri = "تاريخ  اِرْسَالِيَّة"
        ElseIf sOrjinal = "KdvTutari" Then
            sCeviri = "مبلغ الضرائب"
        ElseIf sOrjinal = "Tutar" Then
            sCeviri = "مجموعة"
        ElseIf sOrjinal = "AraToplam" Then
            sCeviri = "المجموع الاول"
        ElseIf sOrjinal = "ToplamIskonto" Then
            sCeviri = "خصم نهائي"
        ElseIf sOrjinal = "ToplamKdv" Then
            sCeviri = "أجمالي الضرائب"
        ElseIf sOrjinal = "GenelToplam" Then
            sCeviri = "المجموع الكلي"
        ElseIf sOrjinal = "Yekun" Then
            sCeviri = "المجموع الكلي"
        ElseIf sOrjinal = "FirmaNo" Then
            sCeviri = "رقم القيد"
        ElseIf sOrjinal = "FirmaKodu" Then
            sCeviri = "رقم كود الشركة"
        ElseIf sOrjinal = "FirmaAdi" Then
            sCeviri = "اسم الشركة"
        ElseIf sOrjinal = "VergiDairesi" Then
            sCeviri = "ضرائب"
        ElseIf sOrjinal = "VergiNo" Then
            sCeviri = "رقم الضرائب"
        ElseIf sOrjinal = "Aciklama1" Then
            sCeviri = "بيانات1"
        ElseIf sOrjinal = "Aciklama2" Then
            sCeviri = "بيانات2"
        ElseIf sOrjinal = "Aciklama3" Then
            sCeviri = "بيانات3"
        ElseIf sOrjinal = "Aciklama4" Then
            sCeviri = "بيانات4"
        ElseIf sOrjinal = "Aciklama5" Then
            sCeviri = "بيانات5"
        ElseIf sOrjinal = "OzelKod" Then
            sCeviri = "كود خاص "
        ElseIf sOrjinal = "OzelKod1" Or sOrjinal = "Sinif1" Then
            sCeviri = "كود خاص 1"
        ElseIf sOrjinal = "OzelKod2" Or sOrjinal = "Sinif2" Then
            sCeviri = "كود خاص 2"
        ElseIf sOrjinal = "OzelKod3" Or sOrjinal = "Sinif3" Then
            sCeviri = "كود خاص 3"
        ElseIf sOrjinal = "OzelKod4" Or sOrjinal = "Sinif4" Then
            sCeviri = "كود خاص 4"
        ElseIf sOrjinal = "OzelKod5" Or sOrjinal = "Sinif5" Then
            sCeviri = "كود خاص 5"
        ElseIf sOrjinal = "OzelKod6" Or sOrjinal = "Sinif6" Then
            sCeviri = "كود خاص 6"
        ElseIf sOrjinal = "OzelKod7" Or sOrjinal = "Sinif7" Then
            sCeviri = "كود خاص 7"
        ElseIf sOrjinal = "OzelKod8" Or sOrjinal = "Sinif8" Then
            sCeviri = "كود خاص 8"
        ElseIf sOrjinal = "OzelKod9" Or sOrjinal = "Sinif9" Then
            sCeviri = "كود خاص 9"
        ElseIf sOrjinal = "OzelKod10" Or sOrjinal = "Sinif10" Then
            sCeviri = "كود خاص 10"
        ElseIf sOrjinal = "OzelKod11" Or sOrjinal = "Sinif11" Then
            sCeviri = "كود خاص 11"
        ElseIf sOrjinal = "OzelKod12" Or sOrjinal = "Sinif12" Then
            sCeviri = "كود خاص 12"
        ElseIf sOrjinal = "OzelKod13" Or sOrjinal = "Sinif13" Then
            sCeviri = "كود خاص 13"
        ElseIf sOrjinal = "OzelKod14" Or sOrjinal = "Sinif14" Then
            sCeviri = "كود خاص 14"
        ElseIf sOrjinal = "OzelKod15" Or sOrjinal = "Sinif15" Then
            sCeviri = "كود خاص 15"
        ElseIf sOrjinal = "Adres" Then
            sCeviri = "العنوان"
        ElseIf sOrjinal = "Tarih" Then
            sCeviri = "تاريخ"
        ElseIf sOrjinal = "BelgeNo" Or sOrjinal = "FisNo" Then
            sCeviri = "رقم اوراق المعلومات"
        ElseIf sOrjinal = "AltBelgeNo" Then
            sCeviri = "رقم اوراق التسلسل الا ضافي"
        ElseIf sOrjinal = "AltBelgeTarihi" Then
            sCeviri = "تاريخ اوراق التسلسل الاضافي"
        ElseIf sOrjinal = "BelgeTipi" Or sOrjinal = "FisTipi" Then
            sCeviri = "نوع الاوراق"
        ElseIf sOrjinal = "Giris" Then
            sCeviri = "دخول"
        ElseIf sOrjinal = "KayitTarihi" Then
            sCeviri = "تاريخ الوضع"
        ElseIf sOrjinal = "Iade" Then
            sCeviri = "مرتجع"
        ElseIf sOrjinal = "Kapali" Then
            sCeviri = "مسدد"
        ElseIf sOrjinal = "OdemeTarihi" Or sOrjinal = "ValorTarihi" Then
            sCeviri = "تاريخ التسديد"
        ElseIf sOrjinal = "OdemeOpsiyonu" Then
            sCeviri = "ترجيح التسديد"
        ElseIf sOrjinal = "CariNo" Then
            sCeviri = "رقم الجاري"
        ElseIf sOrjinal = "Odenen" Then
            sCeviri = "ايداع"
        ElseIf sOrjinal = "AltIskonto1" Then
            sCeviri = "اخر خصم 1"
        ElseIf sOrjinal = "AltIskonto2" Then
            sCeviri = "اخر حصم 2"
        ElseIf sOrjinal = "KdvIskontosu" Then
            sCeviri = "خصم الضرائب"
        ElseIf sOrjinal = "Yuvarla" Then
            sCeviri = "تدوير القيمة"
        ElseIf sOrjinal = "Masraf1" Then
            sCeviri = "مصاريف 1"
        ElseIf sOrjinal = "Masraf2" Then
            sCeviri = "مصاريف 2"
        ElseIf sOrjinal = "Masraf3" Then
            sCeviri = "مصاريف 3"
        ElseIf sOrjinal = "Masraf4" Then
            sCeviri = "مصاريف 4"
        ElseIf sOrjinal = "Masraf5" Then
            sCeviri = "مصاريف 5"
        ElseIf sOrjinal = "Belge" Then
            sCeviri = "ورقة معلومات"
        ElseIf sOrjinal = "Satır" Then
            sCeviri = "خط"
        ElseIf sOrjinal = "Belgeleme" Then
            sCeviri = "عمل الاوراق"
        ElseIf sOrjinal = "Analiz" Then
            sCeviri = "تحليل"
        ElseIf sOrjinal = "Gorunum" Then
            sCeviri = "عرض"
        ElseIf sOrjinal = "TopluIslemler" Then
            sCeviri = "اجمالي الاعمال"
        ElseIf sOrjinal = "Ekran" Then
            sCeviri = "الشاشة"
        ElseIf sOrjinal = "Dosyadan Oku" Then
            sCeviri = "انقل معلومات من الملف"
        ElseIf sOrjinal = "Firma Değiştir" Then
            sCeviri = "غير الشركة"
        ElseIf sOrjinal = "Yeni Belge" Or sOrjinal = "Kaydet Yeni Belge" Then
            sCeviri = "ورقة جديدة"
        ElseIf sOrjinal = "Belge Kopyala" Or sOrjinal = "Fis Kopyala" Then
            sCeviri = "نسخ الورقة"
        ElseIf sOrjinal = "Dizayn" Then
            sCeviri = "ترتيب الاوراق"
        ElseIf sOrjinal = "Önizle" Then
            sCeviri = "معاينة قبل الطباعة"
        ElseIf sOrjinal = "Yazdır" Then
            sCeviri = "اطبع الورقة"
        ElseIf sOrjinal = "Belgeyi İptal Et" Then
            sCeviri = "ابطال الورقة"
        ElseIf sOrjinal = "Çıkış" Then
            sCeviri = "خروج"
        ElseIf sOrjinal = "Satır Ekle" Then
            sCeviri = "اضافة خط"
        ElseIf sOrjinal = "Miktarlı Satır Ekle" Then
            sCeviri = "اضافة خط المبلغ"
        ElseIf sOrjinal = "Satır Sil" Then
            sCeviri = "احذف الخط"
        ElseIf sOrjinal = "Personel Degistir" Then
            sCeviri = "غير الموظف"
        ElseIf sOrjinal = "Maliyet Degistir" Then
            sCeviri = "غير التكلفة"
        ElseIf sOrjinal = "İrsaliyelestirme" Then
            sCeviri = "عمل سندات الشحن"
        ElseIf sOrjinal = "Faturalastirma" Then
            sCeviri = "عمل فاتورة"
        ElseIf sOrjinal = "Stok Fisi" Then
            sCeviri = "بطاقة استوك"
        ElseIf sOrjinal = "Zimmetleme" Then
            sCeviri = "التذميم"
        ElseIf sOrjinal = "Hizli Kapat" Then
            sCeviri = "سدد الحساب سريع"
        ElseIf sOrjinal = "Hesap Kapat" Then
            sCeviri = "سدد الحساب"
        ElseIf sOrjinal = "Bekleyen Siparisler" Then
            sCeviri = "طلبيات با لآنتظار"
        ElseIf sOrjinal = "Alt Belgeler" Then
            sCeviri = "اوراق التسلسل الاضافي"
        ElseIf sOrjinal = "Personel Prim Analizi" Then
            sCeviri = "تحليل نسبة الموظفين"
        ElseIf sOrjinal = "Envanter Analizi" Then
            sCeviri = "تحليل الجرد"
        ElseIf sOrjinal = "Stok Hareket Analizi" Then
            sCeviri = "تحليل حركات استوك"
        ElseIf sOrjinal = "Kar/Zarar Analizi" Then
            sCeviri = "تحليل الربح والخسارة"
        ElseIf sOrjinal = "Kdv Analizi" Then
            sCeviri = "نتحليل الضرائب"
        ElseIf sOrjinal = "Odeme Plani" Then
            sCeviri = "خطة دفعات"
        ElseIf sOrjinal = "Stok Kartı" Then
            sCeviri = "تحليل بطاقة استوك"
        ElseIf sOrjinal = "Cari Kart" Then
            sCeviri = "تحليل بطاقة الجاري"
        ElseIf sOrjinal = "Bakiye Analizi" Then
            sCeviri = "تحليل رصيد الحالي"
        ElseIf sOrjinal = "Toplam" Then
            sCeviri = "الاجمالي"
        ElseIf sOrjinal = "Gorunum Baslik" Then
            sCeviri = "العناوين"
        ElseIf sOrjinal = "Gorunum Hareketler" Then
            sCeviri = "حركات"
        ElseIf sOrjinal = "Gorunum Masraf" Then
            sCeviri = "مصاريف"
        ElseIf sOrjinal = "Gorunum Iskonto" Then
            sCeviri = "خصم مسموح به"
        ElseIf sOrjinal = "Gorunum Toplam" Then
            sCeviri = "المجموع الكلي"
        ElseIf sOrjinal = "Fiyatlandir" Then
            sCeviri = "سعر"
        ElseIf sOrjinal = "Masraflar" Then
            sCeviri = "المصاريف"
        ElseIf sOrjinal = "Satir Birlestir" Then
            sCeviri = "ضم الخط"
        ElseIf sOrjinal = "Fiyat1" Then
            sCeviri = "سعر البيع 1"
        ElseIf sOrjinal = "Fiyat2" Then
            sCeviri = "سعر البيع 2"
        ElseIf sOrjinal = "Fiyat3" Then
            sCeviri = "سعر البيع 3"
        ElseIf sOrjinal = "Fiyat4" Then
            sCeviri = "سعر البيع 4"
        ElseIf sOrjinal = "AlisFiyati" Then
            sCeviri = "شراء"
        ElseIf sOrjinal = "Maliyet" Then
            sCeviri = "التكلفة"
        ElseIf sOrjinal = "Tam Ekran" Then
            sCeviri = "تكبير الشاشة كاملة"
        ElseIf sOrjinal = "Firma Bilgileri" Then
            sCeviri = "معلومات الشركة"
        ElseIf sOrjinal = "Iletisim Bilgileri" Then
            sCeviri = "معلومات العناوين"
        ElseIf sOrjinal = "Yetkili" Then
            sCeviri = "المسؤل"
        ElseIf sOrjinal = "Unvan" Then
            sCeviri = "لقب"
        ElseIf sOrjinal = "Telefon1" Then
            sCeviri = "تليفون 1"
        ElseIf sOrjinal = "Telefon2" Then
            sCeviri = "تليفون 1"
        ElseIf sOrjinal = "Faks" Then
            sCeviri = "فاكس"
        ElseIf sOrjinal = "Gsm" Then
            sCeviri = " هاتف متحرك (موبيل)"
        ElseIf sOrjinal = "EMail" Then
            sCeviri = "عنوان اليكترونيك"
        ElseIf sOrjinal = "Web" Then
            sCeviri = "موقع علي الانترنيت"
        ElseIf sOrjinal = "Tanımlar" Then
            sCeviri = "تعريفات"
        ElseIf sOrjinal = "Finansman" Then
            sCeviri = "دعم مالي"
        ElseIf sOrjinal = "Ek Bilgileri" Then
            sCeviri = "تكملة معلومات"
        ElseIf sOrjinal = "Analiz" Then
            sCeviri = "تحليل"
        ElseIf sOrjinal = "Resim" Then
            sCeviri = "صورة"
        ElseIf sOrjinal = "Kredi Limiti" Then
            sCeviri = "الحد الادني"
        ElseIf sOrjinal = "Risk Limiti" Then
            sCeviri = "حد المجازفة"
        ElseIf sOrjinal = "Opsiyon" Then
            sCeviri = "أختيار"
        ElseIf sOrjinal = "Gecikme Faizi" Then
            sCeviri = "تأخيرات"
        ElseIf sOrjinal = "Aylik Vade" Then
            sCeviri = "فائدة تأخير"
        ElseIf sOrjinal = "Aktif FiyatTipi" Then
            sCeviri = "السعر الفعلي للبيع"
        ElseIf sOrjinal = "Aktif DovizCinsi" Then
            sCeviri = "نوع العملة الفعلية"
        ElseIf sOrjinal = "Aktif" Then
            sCeviri = "فعال"
        ElseIf sOrjinal = "FirmaTipi" Then
            sCeviri = "الشركة"
        ElseIf sOrjinal = "Istihbarat" Then
            sCeviri = "بيانات"
        ElseIf sOrjinal = "Finansal Bilgiler" Then
            sCeviri = "معلومات الدعم المالي"
        ElseIf sOrjinal = "Muhasebe" Then
            sCeviri = "كود حساب المحاسبة"
        ElseIf sOrjinal = "ToplamBorc" Then
            sCeviri = "اجمالي المدين"
        ElseIf sOrjinal = "ToplamAlacak" Then
            sCeviri = "اجمالي الدائن"
        ElseIf sOrjinal = "Bakiye" Then
            sCeviri = "االرصيد"
        ElseIf sOrjinal = "Kredi Durumu" Then
            sCeviri = "الحد الاقص"
        ElseIf sOrjinal = "Risk Durumu" Then
            sCeviri = "حل المجازفة"
        ElseIf sOrjinal = "Acik Hesap Durumu" Then
            sCeviri = "حالة حساب مفتوح"
        ElseIf sOrjinal = "CekSenet Durumu" Then
            sCeviri = "حالة شيك /  سند"
        ElseIf sOrjinal = "Tamam" Then
            sCeviri = "موافق"
        ElseIf sOrjinal = "Vazgec" Then
            sCeviri = "الغاء الآمر"
        ElseIf sOrjinal = "Sil" Then
            sCeviri = "الغاء"
        ElseIf sOrjinal = "Borc Kisa Vadeli" Then
            sCeviri = "مدين موعد قصير"
        ElseIf sOrjinal = "Borc Uzun Vadeli" Then
            sCeviri = "مدين موعد طويل"
        ElseIf sOrjinal = "Alacak Kisa Vadeli" Then
            sCeviri = "دائن موعد قصير"
        ElseIf sOrjinal = "Alacak Uzan Vadeli" Then
            sCeviri = "دائن موعد طويل"
        ElseIf sOrjinal = "Filtrele" Then
            sCeviri = "تصفية"
        ElseIf sOrjinal = "Gruplandir" Then
            sCeviri = "تصنيف"
        ElseIf sOrjinal = "Ara" Then
            sCeviri = "بحث"
        ElseIf sOrjinal = "Gorunumu Duzenle" Then
            sCeviri = "ادارج / حذ ف العمود"
        ElseIf sOrjinal = "Gorunumu Yazdir" Then
            sCeviri = "طباعة العرض"
        ElseIf sOrjinal = "" Then
            sCeviri = ""
        Else
            sCeviri = sOrjinal
        End If
        Return sCeviri
    End Function
End Module
