'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace KontorYukleWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", ConfigurationName:="KontorYukleWS.KontorYuklemeWS")>  _
    Public Interface KontorYuklemeWS
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/sozlesmeTurunuDegistir"& _ 
            "Request", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/sozlesmeTurunuDegistir"& _ 
            "Response"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sozlesmeTurunuDegistir(ByVal request As KontorYukleWS.sozlesmeTurunuDegistirRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> KontorYukleWS.sozlesmeTurunuDegistirResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/sozlesmeTurunuDegistir"& _ 
            "Request", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/sozlesmeTurunuDegistir"& _ 
            "Response")>  _
        Function sozlesmeTurunuDegistirAsync(ByVal request As KontorYukleWS.sozlesmeTurunuDegistirRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.sozlesmeTurunuDegistirResponse)
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/birimTipiyleYuklemeYap"& _ 
            "Request", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/birimTipiyleYuklemeYap"& _ 
            "Response"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function birimTipiyleYuklemeYap(ByVal request As KontorYukleWS.birimTipiyleYuklemeYapRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> KontorYukleWS.birimTipiyleYuklemeYapResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/birimTipiyleYuklemeYap"& _ 
            "Request", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/birimTipiyleYuklemeYap"& _ 
            "Response")>  _
        Function birimTipiyleYuklemeYapAsync(ByVal request As KontorYukleWS.birimTipiyleYuklemeYapRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.birimTipiyleYuklemeYapResponse)
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kalanKontorSorgulaRequ"& _ 
            "est", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kalanKontorSorgulaResp"& _ 
            "onse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function kalanKontorSorgula(ByVal request As KontorYukleWS.kalanKontorSorgulaRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> KontorYukleWS.kalanKontorSorgulaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kalanKontorSorgulaRequ"& _ 
            "est", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kalanKontorSorgulaResp"& _ 
            "onse")>  _
        Function kalanKontorSorgulaAsync(ByVal request As KontorYukleWS.kalanKontorSorgulaRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.kalanKontorSorgulaResponse)
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kredileriDevretRequest"& _ 
            "", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kredileriDevretRespons"& _ 
            "e"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function kredileriDevret(ByVal request As KontorYukleWS.kredileriDevretRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> KontorYukleWS.kredileriDevretResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kredileriDevretRequest"& _ 
            "", ReplyAction:="http://kontoryuklemeservisi.entegrator.com/KontorYuklemeWS/kredileriDevretRespons"& _ 
            "e")>  _
        Function kredileriDevretAsync(ByVal request As KontorYukleWS.kredileriDevretRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.kredileriDevretResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Public Enum Hizmet
        
        '''<remarks/>
        Hepsi
        
        '''<remarks/>
        EArsiv
        
        '''<remarks/>
        EFatura
        
        '''<remarks/>
        EDefter
        
        '''<remarks/>
        EDefterSaklama
        
        '''<remarks/>
        EIrsaliye
        
        '''<remarks/>
        ESerbestMeslek
        
        '''<remarks/>
        EMustahsil
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Public Enum TarifeTuru
        
        '''<remarks/>
        Faturali
        
        '''<remarks/>
        Kontorlu
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Partial Public Class EntResponseUser
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kodField As String
        
        Private aciklamaField As String
        
        Private sebepField As String
        
        Private sonucVerisiField As KrediSonucu
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property kod() As String
            Get
                Return Me.kodField
            End Get
            Set
                Me.kodField = value
                Me.RaisePropertyChanged("kod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property aciklama() As String
            Get
                Return Me.aciklamaField
            End Get
            Set
                Me.aciklamaField = value
                Me.RaisePropertyChanged("aciklama")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property sebep() As String
            Get
                Return Me.sebepField
            End Get
            Set
                Me.sebepField = value
                Me.RaisePropertyChanged("sebep")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property sonucVerisi() As KrediSonucu
            Get
                Return Me.sonucVerisiField
            End Get
            Set
                Me.sonucVerisiField = value
                Me.RaisePropertyChanged("sonucVerisi")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Partial Public Class KrediSonucu
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private toplamFaturaAdediField As Integer
        
        Private toplamAlanBoyutuField As Decimal
        
        Private toplamSayfaMiktariField As Decimal
        
        Private toplamSayfaMiktariFieldSpecified As Boolean
        
        Private harcananGelenFaturaMiktariField As Integer
        
        Private harcananGidenFaturaMiktariField As Integer
        
        Private harcananEArsivFaturaMiktariField As Integer
        
        Private harcananAlanMiktariField As Decimal
        
        Private harcananSayfaMiktariField As Decimal
        
        Private harcananSayfaMiktariFieldSpecified As Boolean
        
        Private harcananEsmmMakbuzMiktariField As Integer
        
        Private harcananEmmMakbuzMiktariField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property toplamFaturaAdedi() As Integer
            Get
                Return Me.toplamFaturaAdediField
            End Get
            Set
                Me.toplamFaturaAdediField = value
                Me.RaisePropertyChanged("toplamFaturaAdedi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property toplamAlanBoyutu() As Decimal
            Get
                Return Me.toplamAlanBoyutuField
            End Get
            Set
                Me.toplamAlanBoyutuField = value
                Me.RaisePropertyChanged("toplamAlanBoyutu")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property toplamSayfaMiktari() As Decimal
            Get
                Return Me.toplamSayfaMiktariField
            End Get
            Set
                Me.toplamSayfaMiktariField = value
                Me.RaisePropertyChanged("toplamSayfaMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property toplamSayfaMiktariSpecified() As Boolean
            Get
                Return Me.toplamSayfaMiktariFieldSpecified
            End Get
            Set
                Me.toplamSayfaMiktariFieldSpecified = value
                Me.RaisePropertyChanged("toplamSayfaMiktariSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property harcananGelenFaturaMiktari() As Integer
            Get
                Return Me.harcananGelenFaturaMiktariField
            End Get
            Set
                Me.harcananGelenFaturaMiktariField = value
                Me.RaisePropertyChanged("harcananGelenFaturaMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property harcananGidenFaturaMiktari() As Integer
            Get
                Return Me.harcananGidenFaturaMiktariField
            End Get
            Set
                Me.harcananGidenFaturaMiktariField = value
                Me.RaisePropertyChanged("harcananGidenFaturaMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property harcananEArsivFaturaMiktari() As Integer
            Get
                Return Me.harcananEArsivFaturaMiktariField
            End Get
            Set
                Me.harcananEArsivFaturaMiktariField = value
                Me.RaisePropertyChanged("harcananEArsivFaturaMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property harcananAlanMiktari() As Decimal
            Get
                Return Me.harcananAlanMiktariField
            End Get
            Set
                Me.harcananAlanMiktariField = value
                Me.RaisePropertyChanged("harcananAlanMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property harcananSayfaMiktari() As Decimal
            Get
                Return Me.harcananSayfaMiktariField
            End Get
            Set
                Me.harcananSayfaMiktariField = value
                Me.RaisePropertyChanged("harcananSayfaMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property harcananSayfaMiktariSpecified() As Boolean
            Get
                Return Me.harcananSayfaMiktariFieldSpecified
            End Get
            Set
                Me.harcananSayfaMiktariFieldSpecified = value
                Me.RaisePropertyChanged("harcananSayfaMiktariSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property harcananEsmmMakbuzMiktari() As Integer
            Get
                Return Me.harcananEsmmMakbuzMiktariField
            End Get
            Set
                Me.harcananEsmmMakbuzMiktariField = value
                Me.RaisePropertyChanged("harcananEsmmMakbuzMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property harcananEmmMakbuzMiktari() As Integer
            Get
                Return Me.harcananEmmMakbuzMiktariField
            End Get
            Set
                Me.harcananEmmMakbuzMiktariField = value
                Me.RaisePropertyChanged("harcananEmmMakbuzMiktari")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Partial Public Class KrediTuru
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private odemeTuruField As OdemeTuru
        
        Private taksitSayisiField As Integer
        
        Private birimMiktariField As Integer
        
        Private baslangicTarihiField As String
        
        Private sonKullanimTarihiField As String
        
        Private faturaNoField As String
        
        Private fiyatField As Decimal
        
        Private fiyatFieldSpecified As Boolean
        
        Private talepEdilenFiyatField As Decimal
        
        Private talepEdilenFiyatFieldSpecified As Boolean
        
        Private aciklamaField As String
        
        Private hediyeTuruField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property odemeTuru() As OdemeTuru
            Get
                Return Me.odemeTuruField
            End Get
            Set
                Me.odemeTuruField = value
                Me.RaisePropertyChanged("odemeTuru")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property taksitSayisi() As Integer
            Get
                Return Me.taksitSayisiField
            End Get
            Set
                Me.taksitSayisiField = value
                Me.RaisePropertyChanged("taksitSayisi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property birimMiktari() As Integer
            Get
                Return Me.birimMiktariField
            End Get
            Set
                Me.birimMiktariField = value
                Me.RaisePropertyChanged("birimMiktari")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property baslangicTarihi() As String
            Get
                Return Me.baslangicTarihiField
            End Get
            Set
                Me.baslangicTarihiField = value
                Me.RaisePropertyChanged("baslangicTarihi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property sonKullanimTarihi() As String
            Get
                Return Me.sonKullanimTarihiField
            End Get
            Set
                Me.sonKullanimTarihiField = value
                Me.RaisePropertyChanged("sonKullanimTarihi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property faturaNo() As String
            Get
                Return Me.faturaNoField
            End Get
            Set
                Me.faturaNoField = value
                Me.RaisePropertyChanged("faturaNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property fiyat() As Decimal
            Get
                Return Me.fiyatField
            End Get
            Set
                Me.fiyatField = value
                Me.RaisePropertyChanged("fiyat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fiyatSpecified() As Boolean
            Get
                Return Me.fiyatFieldSpecified
            End Get
            Set
                Me.fiyatFieldSpecified = value
                Me.RaisePropertyChanged("fiyatSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property talepEdilenFiyat() As Decimal
            Get
                Return Me.talepEdilenFiyatField
            End Get
            Set
                Me.talepEdilenFiyatField = value
                Me.RaisePropertyChanged("talepEdilenFiyat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property talepEdilenFiyatSpecified() As Boolean
            Get
                Return Me.talepEdilenFiyatFieldSpecified
            End Get
            Set
                Me.talepEdilenFiyatFieldSpecified = value
                Me.RaisePropertyChanged("talepEdilenFiyatSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property aciklama() As String
            Get
                Return Me.aciklamaField
            End Get
            Set
                Me.aciklamaField = value
                Me.RaisePropertyChanged("aciklama")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property hediyeTuru() As String
            Get
                Return Me.hediyeTuruField
            End Get
            Set
                Me.hediyeTuruField = value
                Me.RaisePropertyChanged("hediyeTuru")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Public Enum OdemeTuru
        
        '''<remarks/>
        Pesin
        
        '''<remarks/>
        Taksit
        
        '''<remarks/>
        Ucretsiz
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sozlesmeTurunuDegistir", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class sozlesmeTurunuDegistirRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public vknTckn As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public hizmetTuru As KontorYukleWS.Hizmet
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public sozlesmeTuru As KontorYukleWS.TarifeTuru
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vknTckn As String, ByVal hizmetTuru As KontorYukleWS.Hizmet, ByVal sozlesmeTuru As KontorYukleWS.TarifeTuru)
            MyBase.New
            Me.vknTckn = vknTckn
            Me.hizmetTuru = hizmetTuru
            Me.sozlesmeTuru = sozlesmeTuru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sozlesmeTurunuDegistirResponse", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class sozlesmeTurunuDegistirResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As KontorYukleWS.EntResponseUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As KontorYukleWS.EntResponseUser)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Public Enum BirimTuru
        
        '''<remarks/>
        FaturaAdedi
        
        '''<remarks/>
        AlanBoyutu
        
        '''<remarks/>
        ArsivKasa
        
        '''<remarks/>
        Sayfa
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/")>  _
    Public Enum IslemTuru
        
        '''<remarks/>
        Satinalma
        
        '''<remarks/>
        Hediye
        
        '''<remarks/>
        Transfer
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="birimTipiyleYuklemeYap", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class birimTipiyleYuklemeYapRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public vkn_tckn As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public birimTuru As KontorYukleWS.BirimTuru
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public krediTuru As KontorYukleWS.KrediTuru
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public islemTuru As KontorYukleWS.IslemTuru
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru, ByVal krediTuru As KontorYukleWS.KrediTuru, ByVal islemTuru As KontorYukleWS.IslemTuru)
            MyBase.New
            Me.vkn_tckn = vkn_tckn
            Me.birimTuru = birimTuru
            Me.krediTuru = krediTuru
            Me.islemTuru = islemTuru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="birimTipiyleYuklemeYapResponse", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class birimTipiyleYuklemeYapResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As KontorYukleWS.EntResponseUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As KontorYukleWS.EntResponseUser)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="kalanKontorSorgula", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class kalanKontorSorgulaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public vkn_tckn As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public birimTuru As KontorYukleWS.BirimTuru
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru)
            MyBase.New
            Me.vkn_tckn = vkn_tckn
            Me.birimTuru = birimTuru
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="kalanKontorSorgulaResponse", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class kalanKontorSorgulaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As KontorYukleWS.EntResponseUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As KontorYukleWS.EntResponseUser)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="kredileriDevret", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class kredileriDevretRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public kaynak_vkn_tckn As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public hedef_vkn_tckn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal kaynak_vkn_tckn As String, ByVal hedef_vkn_tckn As String)
            MyBase.New
            Me.kaynak_vkn_tckn = kaynak_vkn_tckn
            Me.hedef_vkn_tckn = hedef_vkn_tckn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="kredileriDevretResponse", WrapperNamespace:="http://kontoryuklemeservisi.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class kredileriDevretResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://kontoryuklemeservisi.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As KontorYukleWS.EntResponseUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As KontorYukleWS.EntResponseUser)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface KontorYuklemeWSChannel
        Inherits KontorYukleWS.KontorYuklemeWS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KontorYuklemeWSClient
        Inherits System.ServiceModel.ClientBase(Of KontorYukleWS.KontorYuklemeWS)
        Implements KontorYukleWS.KontorYuklemeWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_sozlesmeTurunuDegistir(ByVal request As KontorYukleWS.sozlesmeTurunuDegistirRequest) As KontorYukleWS.sozlesmeTurunuDegistirResponse Implements KontorYukleWS.KontorYuklemeWS.sozlesmeTurunuDegistir
            Return MyBase.Channel.sozlesmeTurunuDegistir(request)
        End Function
        
        Public Function sozlesmeTurunuDegistir(ByVal vknTckn As String, ByVal hizmetTuru As KontorYukleWS.Hizmet, ByVal sozlesmeTuru As KontorYukleWS.TarifeTuru) As KontorYukleWS.EntResponseUser
            Dim inValue As KontorYukleWS.sozlesmeTurunuDegistirRequest = New KontorYukleWS.sozlesmeTurunuDegistirRequest()
            inValue.vknTckn = vknTckn
            inValue.hizmetTuru = hizmetTuru
            inValue.sozlesmeTuru = sozlesmeTuru
            Dim retVal As KontorYukleWS.sozlesmeTurunuDegistirResponse = CType(Me,KontorYukleWS.KontorYuklemeWS).sozlesmeTurunuDegistir(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_sozlesmeTurunuDegistirAsync(ByVal request As KontorYukleWS.sozlesmeTurunuDegistirRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.sozlesmeTurunuDegistirResponse) Implements KontorYukleWS.KontorYuklemeWS.sozlesmeTurunuDegistirAsync
            Return MyBase.Channel.sozlesmeTurunuDegistirAsync(request)
        End Function
        
        Public Function sozlesmeTurunuDegistirAsync(ByVal vknTckn As String, ByVal hizmetTuru As KontorYukleWS.Hizmet, ByVal sozlesmeTuru As KontorYukleWS.TarifeTuru) As System.Threading.Tasks.Task(Of KontorYukleWS.sozlesmeTurunuDegistirResponse)
            Dim inValue As KontorYukleWS.sozlesmeTurunuDegistirRequest = New KontorYukleWS.sozlesmeTurunuDegistirRequest()
            inValue.vknTckn = vknTckn
            inValue.hizmetTuru = hizmetTuru
            inValue.sozlesmeTuru = sozlesmeTuru
            Return CType(Me,KontorYukleWS.KontorYuklemeWS).sozlesmeTurunuDegistirAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_birimTipiyleYuklemeYap(ByVal request As KontorYukleWS.birimTipiyleYuklemeYapRequest) As KontorYukleWS.birimTipiyleYuklemeYapResponse Implements KontorYukleWS.KontorYuklemeWS.birimTipiyleYuklemeYap
            Return MyBase.Channel.birimTipiyleYuklemeYap(request)
        End Function
        
        Public Function birimTipiyleYuklemeYap(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru, ByVal krediTuru As KontorYukleWS.KrediTuru, ByVal islemTuru As KontorYukleWS.IslemTuru) As KontorYukleWS.EntResponseUser
            Dim inValue As KontorYukleWS.birimTipiyleYuklemeYapRequest = New KontorYukleWS.birimTipiyleYuklemeYapRequest()
            inValue.vkn_tckn = vkn_tckn
            inValue.birimTuru = birimTuru
            inValue.krediTuru = krediTuru
            inValue.islemTuru = islemTuru
            Dim retVal As KontorYukleWS.birimTipiyleYuklemeYapResponse = CType(Me,KontorYukleWS.KontorYuklemeWS).birimTipiyleYuklemeYap(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_birimTipiyleYuklemeYapAsync(ByVal request As KontorYukleWS.birimTipiyleYuklemeYapRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.birimTipiyleYuklemeYapResponse) Implements KontorYukleWS.KontorYuklemeWS.birimTipiyleYuklemeYapAsync
            Return MyBase.Channel.birimTipiyleYuklemeYapAsync(request)
        End Function
        
        Public Function birimTipiyleYuklemeYapAsync(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru, ByVal krediTuru As KontorYukleWS.KrediTuru, ByVal islemTuru As KontorYukleWS.IslemTuru) As System.Threading.Tasks.Task(Of KontorYukleWS.birimTipiyleYuklemeYapResponse)
            Dim inValue As KontorYukleWS.birimTipiyleYuklemeYapRequest = New KontorYukleWS.birimTipiyleYuklemeYapRequest()
            inValue.vkn_tckn = vkn_tckn
            inValue.birimTuru = birimTuru
            inValue.krediTuru = krediTuru
            inValue.islemTuru = islemTuru
            Return CType(Me,KontorYukleWS.KontorYuklemeWS).birimTipiyleYuklemeYapAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_kalanKontorSorgula(ByVal request As KontorYukleWS.kalanKontorSorgulaRequest) As KontorYukleWS.kalanKontorSorgulaResponse Implements KontorYukleWS.KontorYuklemeWS.kalanKontorSorgula
            Return MyBase.Channel.kalanKontorSorgula(request)
        End Function
        
        Public Function kalanKontorSorgula(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru) As KontorYukleWS.EntResponseUser
            Dim inValue As KontorYukleWS.kalanKontorSorgulaRequest = New KontorYukleWS.kalanKontorSorgulaRequest()
            inValue.vkn_tckn = vkn_tckn
            inValue.birimTuru = birimTuru
            Dim retVal As KontorYukleWS.kalanKontorSorgulaResponse = CType(Me,KontorYukleWS.KontorYuklemeWS).kalanKontorSorgula(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_kalanKontorSorgulaAsync(ByVal request As KontorYukleWS.kalanKontorSorgulaRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.kalanKontorSorgulaResponse) Implements KontorYukleWS.KontorYuklemeWS.kalanKontorSorgulaAsync
            Return MyBase.Channel.kalanKontorSorgulaAsync(request)
        End Function
        
        Public Function kalanKontorSorgulaAsync(ByVal vkn_tckn As String, ByVal birimTuru As KontorYukleWS.BirimTuru) As System.Threading.Tasks.Task(Of KontorYukleWS.kalanKontorSorgulaResponse)
            Dim inValue As KontorYukleWS.kalanKontorSorgulaRequest = New KontorYukleWS.kalanKontorSorgulaRequest()
            inValue.vkn_tckn = vkn_tckn
            inValue.birimTuru = birimTuru
            Return CType(Me,KontorYukleWS.KontorYuklemeWS).kalanKontorSorgulaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_kredileriDevret(ByVal request As KontorYukleWS.kredileriDevretRequest) As KontorYukleWS.kredileriDevretResponse Implements KontorYukleWS.KontorYuklemeWS.kredileriDevret
            Return MyBase.Channel.kredileriDevret(request)
        End Function
        
        Public Function kredileriDevret(ByVal kaynak_vkn_tckn As String, ByVal hedef_vkn_tckn As String) As KontorYukleWS.EntResponseUser
            Dim inValue As KontorYukleWS.kredileriDevretRequest = New KontorYukleWS.kredileriDevretRequest()
            inValue.kaynak_vkn_tckn = kaynak_vkn_tckn
            inValue.hedef_vkn_tckn = hedef_vkn_tckn
            Dim retVal As KontorYukleWS.kredileriDevretResponse = CType(Me,KontorYukleWS.KontorYuklemeWS).kredileriDevret(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KontorYukleWS_KontorYuklemeWS_kredileriDevretAsync(ByVal request As KontorYukleWS.kredileriDevretRequest) As System.Threading.Tasks.Task(Of KontorYukleWS.kredileriDevretResponse) Implements KontorYukleWS.KontorYuklemeWS.kredileriDevretAsync
            Return MyBase.Channel.kredileriDevretAsync(request)
        End Function
        
        Public Function kredileriDevretAsync(ByVal kaynak_vkn_tckn As String, ByVal hedef_vkn_tckn As String) As System.Threading.Tasks.Task(Of KontorYukleWS.kredileriDevretResponse)
            Dim inValue As KontorYukleWS.kredileriDevretRequest = New KontorYukleWS.kredileriDevretRequest()
            inValue.kaynak_vkn_tckn = kaynak_vkn_tckn
            inValue.hedef_vkn_tckn = hedef_vkn_tckn
            Return CType(Me,KontorYukleWS.KontorYuklemeWS).kredileriDevretAsync(inValue)
        End Function
    End Class
End Namespace
