'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Otomatik Kaydetme İşlevi"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=(LOCAL);Persist Security Info=True;User ID=sa;Initi"& _ 
            "al Catalog=EKSEN")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
        
        ' ===== E-TICARET SENKRON CHECKBOX AYARLARI =====
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTumStoklar() As Boolean
            Get
                Return CType(Me("EticaretTumStoklar"),Boolean)
            End Get
            Set
                Me("EticaretTumStoklar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretFiyatDegisenleri() As Boolean
            Get
                Return CType(Me("EticaretFiyatDegisenleri"),Boolean)
            End Get
            Set
                Me("EticaretFiyatDegisenleri") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretMiktarDegisenleri() As Boolean
            Get
                Return CType(Me("EticaretMiktarDegisenleri"),Boolean)
            End Get
            Set
                Me("EticaretMiktarDegisenleri") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretResimGonder() As Boolean
            Get
                Return CType(Me("EticaretResimGonder"),Boolean)
            End Get
            Set
                Me("EticaretResimGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretVaryantGuncelle() As Boolean
            Get
                Return CType(Me("EticaretVaryantGuncelle"),Boolean)
            End Get
            Set
                Me("EticaretVaryantGuncelle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretKategoriGuncelle() As Boolean
            Get
                Return CType(Me("EticaretKategoriGuncelle"),Boolean)
            End Get
            Set
                Me("EticaretKategoriGuncelle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretSiparisAl() As Boolean
            Get
                Return CType(Me("EticaretSiparisAl"),Boolean)
            End Get
            Set
                Me("EticaretSiparisAl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTumSiparisler() As Boolean
            Get
                Return CType(Me("EticaretTumSiparisler"),Boolean)
            End Get
            Set
                Me("EticaretTumSiparisler") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretPazaryeriFiyatlari() As Boolean
            Get
                Return CType(Me("EticaretPazaryeriFiyatlari"),Boolean)
            End Get
            Set
                Me("EticaretPazaryeriFiyatlari") = value
            End Set
        End Property
        
        ' ===== TRIGGER CHECKBOX AYARLARI =====
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTriggerAktif() As Boolean
            Get
                Return CType(Me("EticaretTriggerAktif"),Boolean)
            End Get
            Set
                Me("EticaretTriggerAktif") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTriggerStok() As Boolean
            Get
                Return CType(Me("EticaretTriggerStok"),Boolean)
            End Get
            Set
                Me("EticaretTriggerStok") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTriggerFiyat() As Boolean
            Get
                Return CType(Me("EticaretTriggerFiyat"),Boolean)
            End Get
            Set
                Me("EticaretTriggerFiyat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTriggerResim() As Boolean
            Get
                Return CType(Me("EticaretTriggerResim"),Boolean)
            End Get
            Set
                Me("EticaretTriggerResim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTriggerKategori() As Boolean
            Get
                Return CType(Me("EticaretTriggerKategori"),Boolean)
            End Get
            Set
                Me("EticaretTriggerKategori") = value
            End Set
        End Property
        
        ' ===== DIGER CHECKBOX AYARLARI =====
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretTumunuGonder() As Boolean
            Get
                Return CType(Me("EticaretTumunuGonder"),Boolean)
            End Get
            Set
                Me("EticaretTumunuGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretMarkaGonder() As Boolean
            Get
                Return CType(Me("EticaretMarkaGonder"),Boolean)
            End Get
            Set
                Me("EticaretMarkaGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretKategoriGonder() As Boolean
            Get
                Return CType(Me("EticaretKategoriGonder"),Boolean)
            End Get
            Set
                Me("EticaretKategoriGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretUzunAciklamaGonder() As Boolean
            Get
                Return CType(Me("EticaretUzunAciklamaGonder"),Boolean)
            End Get
            Set
                Me("EticaretUzunAciklamaGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretKisaAciklamaGonder() As Boolean
            Get
                Return CType(Me("EticaretKisaAciklamaGonder"),Boolean)
            End Get
            Set
                Me("EticaretKisaAciklamaGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretSEOGonder() As Boolean
            Get
                Return CType(Me("EticaretSEOGonder"),Boolean)
            End Get
            Set
                Me("EticaretSEOGonder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EticaretDesiGonder() As Boolean
            Get
                Return CType(Me("EticaretDesiGonder"),Boolean)
            End Get
            Set
                Me("EticaretDesiGonder") = value
            End Set
        End Property
        
        ' ===== TIMER SURE AYARLARI (DAKIKA) =====
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property EticaretStokTimerDakika() As Integer
            Get
                Return CType(Me("EticaretStokTimerDakika"),Integer)
            End Get
            Set
                Me("EticaretStokTimerDakika") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property EticaretSiparisTimerDakika() As Integer
            Get
                Return CType(Me("EticaretSiparisTimerDakika"),Integer)
            End Get
            Set
                Me("EticaretSiparisTimerDakika") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property EticaretTriggerTimerDakika() As Integer
            Get
                Return CType(Me("EticaretTriggerTimerDakika"),Integer)
            End Get
            Set
                Me("EticaretTriggerTimerDakika") = value
            End Set
        End Property
        
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.business_smart.My.MySettings
            Get
                Return Global.business_smart.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
