'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace eArsivGelen
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", ConfigurationName:="eArsivGelen.LoadInvoiceWS")>  _
    Public Interface LoadInvoiceWS
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/loadInvoiceRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/loadInvoiceResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function loadInvoice(ByVal request As eArsivGelen.loadInvoiceRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> eArsivGelen.loadInvoiceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/loadInvoiceRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/loadInvoiceResponse")>  _
        Function loadInvoiceAsync(ByVal request As eArsivGelen.loadInvoiceRequest) As System.Threading.Tasks.Task(Of eArsivGelen.loadInvoiceResponse)
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoiceRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoiceResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function QueryInvoice(ByVal request As eArsivGelen.QueryInvoiceRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> eArsivGelen.QueryInvoiceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoiceRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoiceResponse")>  _
        Function QueryInvoiceAsync(ByVal request As eArsivGelen.QueryInvoiceRequest) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoiceResponse)
        
        'CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoicesWithDocu"& _ 
            "mentDateRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoicesWithDocu"& _ 
            "mentDateResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function QueryInvoicesWithDocumentDate(ByVal request As eArsivGelen.QueryInvoicesWithDocumentDateRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> eArsivGelen.QueryInvoicesWithDocumentDateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoicesWithDocu"& _ 
            "mentDateRequest", ReplyAction:="http://eainvoiceloadingservice.entegrator.com/LoadInvoiceWS/QueryInvoicesWithDocu"& _ 
            "mentDateResponse")>  _
        Function QueryInvoicesWithDocumentDateAsync(ByVal request As eArsivGelen.QueryInvoicesWithDocumentDateRequest) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoicesWithDocumentDateResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class InputDocument
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private documentUUIDField As String
        
        Private xmlContentField As String
        
        Private sourceUrnField As String
        
        Private destinationUrnField As String
        
        Private documentNoPrefixField As String
        
        Private localIdField As String
        
        Private documentIdField As String
        
        Private submitForApprovalField As Boolean
        
        Private submitForApprovalFieldSpecified As Boolean
        
        Private documentDateField As String
        
        Private noteField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property documentUUID() As String
            Get
                Return Me.documentUUIDField
            End Get
            Set
                Me.documentUUIDField = value
                Me.RaisePropertyChanged("documentUUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property xmlContent() As String
            Get
                Return Me.xmlContentField
            End Get
            Set
                Me.xmlContentField = value
                Me.RaisePropertyChanged("xmlContent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property sourceUrn() As String
            Get
                Return Me.sourceUrnField
            End Get
            Set
                Me.sourceUrnField = value
                Me.RaisePropertyChanged("sourceUrn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property destinationUrn() As String
            Get
                Return Me.destinationUrnField
            End Get
            Set
                Me.destinationUrnField = value
                Me.RaisePropertyChanged("destinationUrn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property documentNoPrefix() As String
            Get
                Return Me.documentNoPrefixField
            End Get
            Set
                Me.documentNoPrefixField = value
                Me.RaisePropertyChanged("documentNoPrefix")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property localId() As String
            Get
                Return Me.localIdField
            End Get
            Set
                Me.localIdField = value
                Me.RaisePropertyChanged("localId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property documentId() As String
            Get
                Return Me.documentIdField
            End Get
            Set
                Me.documentIdField = value
                Me.RaisePropertyChanged("documentId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property submitForApproval() As Boolean
            Get
                Return Me.submitForApprovalField
            End Get
            Set
                Me.submitForApprovalField = value
                Me.RaisePropertyChanged("submitForApproval")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property submitForApprovalSpecified() As Boolean
            Get
                Return Me.submitForApprovalFieldSpecified
            End Get
            Set
                Me.submitForApprovalFieldSpecified = value
                Me.RaisePropertyChanged("submitForApprovalSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property documentDate() As String
            Get
                Return Me.documentDateField
            End Get
            Set
                Me.documentDateField = value
                Me.RaisePropertyChanged("documentDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property note() As String
            Get
                Return Me.noteField
            End Get
            Set
                Me.noteField = value
                Me.RaisePropertyChanged("note")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class TaxInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private taxtTypeCodeField As String
        
        Private taxtTypeNameField As String
        
        Private taxAmountField As String
        
        Private taxPercentageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property taxtTypeCode() As String
            Get
                Return Me.taxtTypeCodeField
            End Get
            Set
                Me.taxtTypeCodeField = value
                Me.RaisePropertyChanged("taxtTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property taxtTypeName() As String
            Get
                Return Me.taxtTypeNameField
            End Get
            Set
                Me.taxtTypeNameField = value
                Me.RaisePropertyChanged("taxtTypeName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property taxAmount() As String
            Get
                Return Me.taxAmountField
            End Get
            Set
                Me.taxAmountField = value
                Me.RaisePropertyChanged("taxAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property taxPercentage() As String
            Get
                Return Me.taxPercentageField
            End Get
            Set
                Me.taxPercentageField = value
                Me.RaisePropertyChanged("taxPercentage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class DocumentInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private documentDateField As String
        
        Private documentNoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property documentDate() As String
            Get
                Return Me.documentDateField
            End Get
            Set
                Me.documentDateField = value
                Me.RaisePropertyChanged("documentDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property documentNo() As String
            Get
                Return Me.documentNoField
            End Get
            Set
                Me.documentNoField = value
                Me.RaisePropertyChanged("documentNo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class ResponseDocument
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private document_uuidField As String
        
        Private document_idField As String
        
        Private envelope_uuidField As String
        
        Private document_profileField As String
        
        Private system_creation_timeField As String
        
        Private document_issue_dateField As String
        
        Private source_idField As String
        
        Private destination_idField As String
        
        Private source_urnField As String
        
        Private source_titleField As String
        
        Private destination_urnField As String
        
        Private currency_codeField As String
        
        Private invoice_totalField As String
        
        Private state_codeField As String
        
        Private state_explanationField As String
        
        Private causeField As String
        
        Private content_typeField As String
        
        Private document_contentField() As Byte
        
        Private emailSentField As Integer
        
        Private emailSentDateField As String
        
        Private cancelledField As String
        
        Private cancel_dateField As String
        
        Private reference_document_uuidField As String
        
        Private response_document_uuidField As String
        
        Private response_codeField As String
        
        Private response_validation_stateField As String
        
        Private response_received_dateField As String
        
        Private gtb_reference_noField As String
        
        Private gtb_gcb_tescil_noField As String
        
        Private gtb_fiili_ihracat_tarihiField As String
        
        Private reserved1Field As String
        
        Private reserved2Field As String
        
        Private reserved3Field As String
        
        Private document_type_codeField As String
        
        Private notesField() As String
        
        Private despatchInfoField() As DocumentInfo
        
        Private orderInfoField As DocumentInfo
        
        Private taxInfoField() As TaxInfo
        
        Private taxInclusiveAmountField As String
        
        Private taxExlusiveAmountField As String
        
        Private allowanceTotalAmountField As String
        
        Private taxAmount0015Field As String
        
        Private lineExtensionAmountField As String
        
        Private suplierPersonNameField As String
        
        Private supplierPersonMiddleNameField As String
        
        Private supplierPersonFamilyNameField As String
        
        Private customerPersonNameField As String
        
        Private customerPersonMiddleNameField As String
        
        Private customerPersonFamilyNameField As String
        
        Private destination_titleField As String
        
        Private is_readField As String
        
        Private is_archievedField As String
        
        Private is_accountedField As String
        
        Private is_transferredField As String
        
        Private is_printedField As String
        
        Private local_idField As String
        
        Private sendingTypeField As String
        
        Private buyerCustomerPartyNameField As String
        
        Private buyerCustomerPersonNameField As String
        
        Private buyerCustomerPersonFamilyNameField As String
        
        Private report_noField As String
        
        Private cancel_report_noField As String
        
        Private objectedField As String
        
        Private objectionReasonField As String
        
        Private objectionDateField As String
        
        Private objectionReportNoField As String
        
        Private objectionTypeField As String
        
        Private objectionDocumentNoField As String
        
        Private destinationEmailField As String
        
        Private destinationMobileField As String
        
        Private smsSentDateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property document_uuid() As String
            Get
                Return Me.document_uuidField
            End Get
            Set
                Me.document_uuidField = value
                Me.RaisePropertyChanged("document_uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property document_id() As String
            Get
                Return Me.document_idField
            End Get
            Set
                Me.document_idField = value
                Me.RaisePropertyChanged("document_id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property envelope_uuid() As String
            Get
                Return Me.envelope_uuidField
            End Get
            Set
                Me.envelope_uuidField = value
                Me.RaisePropertyChanged("envelope_uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property document_profile() As String
            Get
                Return Me.document_profileField
            End Get
            Set
                Me.document_profileField = value
                Me.RaisePropertyChanged("document_profile")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property system_creation_time() As String
            Get
                Return Me.system_creation_timeField
            End Get
            Set
                Me.system_creation_timeField = value
                Me.RaisePropertyChanged("system_creation_time")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property document_issue_date() As String
            Get
                Return Me.document_issue_dateField
            End Get
            Set
                Me.document_issue_dateField = value
                Me.RaisePropertyChanged("document_issue_date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property source_id() As String
            Get
                Return Me.source_idField
            End Get
            Set
                Me.source_idField = value
                Me.RaisePropertyChanged("source_id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property destination_id() As String
            Get
                Return Me.destination_idField
            End Get
            Set
                Me.destination_idField = value
                Me.RaisePropertyChanged("destination_id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property source_urn() As String
            Get
                Return Me.source_urnField
            End Get
            Set
                Me.source_urnField = value
                Me.RaisePropertyChanged("source_urn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property source_title() As String
            Get
                Return Me.source_titleField
            End Get
            Set
                Me.source_titleField = value
                Me.RaisePropertyChanged("source_title")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property destination_urn() As String
            Get
                Return Me.destination_urnField
            End Get
            Set
                Me.destination_urnField = value
                Me.RaisePropertyChanged("destination_urn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property currency_code() As String
            Get
                Return Me.currency_codeField
            End Get
            Set
                Me.currency_codeField = value
                Me.RaisePropertyChanged("currency_code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property invoice_total() As String
            Get
                Return Me.invoice_totalField
            End Get
            Set
                Me.invoice_totalField = value
                Me.RaisePropertyChanged("invoice_total")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property state_code() As String
            Get
                Return Me.state_codeField
            End Get
            Set
                Me.state_codeField = value
                Me.RaisePropertyChanged("state_code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property state_explanation() As String
            Get
                Return Me.state_explanationField
            End Get
            Set
                Me.state_explanationField = value
                Me.RaisePropertyChanged("state_explanation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property cause() As String
            Get
                Return Me.causeField
            End Get
            Set
                Me.causeField = value
                Me.RaisePropertyChanged("cause")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property content_type() As String
            Get
                Return Me.content_typeField
            End Get
            Set
                Me.content_typeField = value
                Me.RaisePropertyChanged("content_type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=17)>  _
        Public Property document_content() As Byte()
            Get
                Return Me.document_contentField
            End Get
            Set
                Me.document_contentField = value
                Me.RaisePropertyChanged("document_content")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property emailSent() As Integer
            Get
                Return Me.emailSentField
            End Get
            Set
                Me.emailSentField = value
                Me.RaisePropertyChanged("emailSent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property emailSentDate() As String
            Get
                Return Me.emailSentDateField
            End Get
            Set
                Me.emailSentDateField = value
                Me.RaisePropertyChanged("emailSentDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property cancelled() As String
            Get
                Return Me.cancelledField
            End Get
            Set
                Me.cancelledField = value
                Me.RaisePropertyChanged("cancelled")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property cancel_date() As String
            Get
                Return Me.cancel_dateField
            End Get
            Set
                Me.cancel_dateField = value
                Me.RaisePropertyChanged("cancel_date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=22)>  _
        Public Property reference_document_uuid() As String
            Get
                Return Me.reference_document_uuidField
            End Get
            Set
                Me.reference_document_uuidField = value
                Me.RaisePropertyChanged("reference_document_uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=23)>  _
        Public Property response_document_uuid() As String
            Get
                Return Me.response_document_uuidField
            End Get
            Set
                Me.response_document_uuidField = value
                Me.RaisePropertyChanged("response_document_uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=24)>  _
        Public Property response_code() As String
            Get
                Return Me.response_codeField
            End Get
            Set
                Me.response_codeField = value
                Me.RaisePropertyChanged("response_code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=25)>  _
        Public Property response_validation_state() As String
            Get
                Return Me.response_validation_stateField
            End Get
            Set
                Me.response_validation_stateField = value
                Me.RaisePropertyChanged("response_validation_state")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=26)>  _
        Public Property response_received_date() As String
            Get
                Return Me.response_received_dateField
            End Get
            Set
                Me.response_received_dateField = value
                Me.RaisePropertyChanged("response_received_date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=27)>  _
        Public Property gtb_reference_no() As String
            Get
                Return Me.gtb_reference_noField
            End Get
            Set
                Me.gtb_reference_noField = value
                Me.RaisePropertyChanged("gtb_reference_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=28)>  _
        Public Property gtb_gcb_tescil_no() As String
            Get
                Return Me.gtb_gcb_tescil_noField
            End Get
            Set
                Me.gtb_gcb_tescil_noField = value
                Me.RaisePropertyChanged("gtb_gcb_tescil_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=29)>  _
        Public Property gtb_fiili_ihracat_tarihi() As String
            Get
                Return Me.gtb_fiili_ihracat_tarihiField
            End Get
            Set
                Me.gtb_fiili_ihracat_tarihiField = value
                Me.RaisePropertyChanged("gtb_fiili_ihracat_tarihi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=30)>  _
        Public Property reserved1() As String
            Get
                Return Me.reserved1Field
            End Get
            Set
                Me.reserved1Field = value
                Me.RaisePropertyChanged("reserved1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=31)>  _
        Public Property reserved2() As String
            Get
                Return Me.reserved2Field
            End Get
            Set
                Me.reserved2Field = value
                Me.RaisePropertyChanged("reserved2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=32)>  _
        Public Property reserved3() As String
            Get
                Return Me.reserved3Field
            End Get
            Set
                Me.reserved3Field = value
                Me.RaisePropertyChanged("reserved3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=33)>  _
        Public Property document_type_code() As String
            Get
                Return Me.document_type_codeField
            End Get
            Set
                Me.document_type_codeField = value
                Me.RaisePropertyChanged("document_type_code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("notes", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=34)>  _
        Public Property notes() As String()
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
                Me.RaisePropertyChanged("notes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("despatchInfo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=35)>  _
        Public Property despatchInfo() As DocumentInfo()
            Get
                Return Me.despatchInfoField
            End Get
            Set
                Me.despatchInfoField = value
                Me.RaisePropertyChanged("despatchInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=36)>  _
        Public Property orderInfo() As DocumentInfo
            Get
                Return Me.orderInfoField
            End Get
            Set
                Me.orderInfoField = value
                Me.RaisePropertyChanged("orderInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("taxInfo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=37)>  _
        Public Property taxInfo() As TaxInfo()
            Get
                Return Me.taxInfoField
            End Get
            Set
                Me.taxInfoField = value
                Me.RaisePropertyChanged("taxInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=38)>  _
        Public Property taxInclusiveAmount() As String
            Get
                Return Me.taxInclusiveAmountField
            End Get
            Set
                Me.taxInclusiveAmountField = value
                Me.RaisePropertyChanged("taxInclusiveAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=39)>  _
        Public Property taxExlusiveAmount() As String
            Get
                Return Me.taxExlusiveAmountField
            End Get
            Set
                Me.taxExlusiveAmountField = value
                Me.RaisePropertyChanged("taxExlusiveAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=40)>  _
        Public Property allowanceTotalAmount() As String
            Get
                Return Me.allowanceTotalAmountField
            End Get
            Set
                Me.allowanceTotalAmountField = value
                Me.RaisePropertyChanged("allowanceTotalAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=41)>  _
        Public Property taxAmount0015() As String
            Get
                Return Me.taxAmount0015Field
            End Get
            Set
                Me.taxAmount0015Field = value
                Me.RaisePropertyChanged("taxAmount0015")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=42)>  _
        Public Property lineExtensionAmount() As String
            Get
                Return Me.lineExtensionAmountField
            End Get
            Set
                Me.lineExtensionAmountField = value
                Me.RaisePropertyChanged("lineExtensionAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=43)>  _
        Public Property suplierPersonName() As String
            Get
                Return Me.suplierPersonNameField
            End Get
            Set
                Me.suplierPersonNameField = value
                Me.RaisePropertyChanged("suplierPersonName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=44)>  _
        Public Property supplierPersonMiddleName() As String
            Get
                Return Me.supplierPersonMiddleNameField
            End Get
            Set
                Me.supplierPersonMiddleNameField = value
                Me.RaisePropertyChanged("supplierPersonMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=45)>  _
        Public Property supplierPersonFamilyName() As String
            Get
                Return Me.supplierPersonFamilyNameField
            End Get
            Set
                Me.supplierPersonFamilyNameField = value
                Me.RaisePropertyChanged("supplierPersonFamilyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=46)>  _
        Public Property customerPersonName() As String
            Get
                Return Me.customerPersonNameField
            End Get
            Set
                Me.customerPersonNameField = value
                Me.RaisePropertyChanged("customerPersonName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=47)>  _
        Public Property customerPersonMiddleName() As String
            Get
                Return Me.customerPersonMiddleNameField
            End Get
            Set
                Me.customerPersonMiddleNameField = value
                Me.RaisePropertyChanged("customerPersonMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=48)>  _
        Public Property customerPersonFamilyName() As String
            Get
                Return Me.customerPersonFamilyNameField
            End Get
            Set
                Me.customerPersonFamilyNameField = value
                Me.RaisePropertyChanged("customerPersonFamilyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=49)>  _
        Public Property destination_title() As String
            Get
                Return Me.destination_titleField
            End Get
            Set
                Me.destination_titleField = value
                Me.RaisePropertyChanged("destination_title")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=50)>  _
        Public Property is_read() As String
            Get
                Return Me.is_readField
            End Get
            Set
                Me.is_readField = value
                Me.RaisePropertyChanged("is_read")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=51)>  _
        Public Property is_archieved() As String
            Get
                Return Me.is_archievedField
            End Get
            Set
                Me.is_archievedField = value
                Me.RaisePropertyChanged("is_archieved")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=52)>  _
        Public Property is_accounted() As String
            Get
                Return Me.is_accountedField
            End Get
            Set
                Me.is_accountedField = value
                Me.RaisePropertyChanged("is_accounted")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=53)>  _
        Public Property is_transferred() As String
            Get
                Return Me.is_transferredField
            End Get
            Set
                Me.is_transferredField = value
                Me.RaisePropertyChanged("is_transferred")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=54)>  _
        Public Property is_printed() As String
            Get
                Return Me.is_printedField
            End Get
            Set
                Me.is_printedField = value
                Me.RaisePropertyChanged("is_printed")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=55)>  _
        Public Property local_id() As String
            Get
                Return Me.local_idField
            End Get
            Set
                Me.local_idField = value
                Me.RaisePropertyChanged("local_id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=56)>  _
        Public Property sendingType() As String
            Get
                Return Me.sendingTypeField
            End Get
            Set
                Me.sendingTypeField = value
                Me.RaisePropertyChanged("sendingType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=57)>  _
        Public Property buyerCustomerPartyName() As String
            Get
                Return Me.buyerCustomerPartyNameField
            End Get
            Set
                Me.buyerCustomerPartyNameField = value
                Me.RaisePropertyChanged("buyerCustomerPartyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=58)>  _
        Public Property buyerCustomerPersonName() As String
            Get
                Return Me.buyerCustomerPersonNameField
            End Get
            Set
                Me.buyerCustomerPersonNameField = value
                Me.RaisePropertyChanged("buyerCustomerPersonName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=59)>  _
        Public Property buyerCustomerPersonFamilyName() As String
            Get
                Return Me.buyerCustomerPersonFamilyNameField
            End Get
            Set
                Me.buyerCustomerPersonFamilyNameField = value
                Me.RaisePropertyChanged("buyerCustomerPersonFamilyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=60)>  _
        Public Property report_no() As String
            Get
                Return Me.report_noField
            End Get
            Set
                Me.report_noField = value
                Me.RaisePropertyChanged("report_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=61)>  _
        Public Property cancel_report_no() As String
            Get
                Return Me.cancel_report_noField
            End Get
            Set
                Me.cancel_report_noField = value
                Me.RaisePropertyChanged("cancel_report_no")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=62)>  _
        Public Property objected() As String
            Get
                Return Me.objectedField
            End Get
            Set
                Me.objectedField = value
                Me.RaisePropertyChanged("objected")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=63)>  _
        Public Property objectionReason() As String
            Get
                Return Me.objectionReasonField
            End Get
            Set
                Me.objectionReasonField = value
                Me.RaisePropertyChanged("objectionReason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=64)>  _
        Public Property objectionDate() As String
            Get
                Return Me.objectionDateField
            End Get
            Set
                Me.objectionDateField = value
                Me.RaisePropertyChanged("objectionDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=65)>  _
        Public Property objectionReportNo() As String
            Get
                Return Me.objectionReportNoField
            End Get
            Set
                Me.objectionReportNoField = value
                Me.RaisePropertyChanged("objectionReportNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=66)>  _
        Public Property objectionType() As String
            Get
                Return Me.objectionTypeField
            End Get
            Set
                Me.objectionTypeField = value
                Me.RaisePropertyChanged("objectionType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=67)>  _
        Public Property objectionDocumentNo() As String
            Get
                Return Me.objectionDocumentNoField
            End Get
            Set
                Me.objectionDocumentNoField = value
                Me.RaisePropertyChanged("objectionDocumentNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=68)>  _
        Public Property destinationEmail() As String
            Get
                Return Me.destinationEmailField
            End Get
            Set
                Me.destinationEmailField = value
                Me.RaisePropertyChanged("destinationEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=69)>  _
        Public Property destinationMobile() As String
            Get
                Return Me.destinationMobileField
            End Get
            Set
                Me.destinationMobileField = value
                Me.RaisePropertyChanged("destinationMobile")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=70)>  _
        Public Property smsSentDate() As String
            Get
                Return Me.smsSentDateField
            End Get
            Set
                Me.smsSentDateField = value
                Me.RaisePropertyChanged("smsSentDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class DocumentQueryResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private queryStateField As Integer
        
        Private stateExplanationField As String
        
        Private documentsCountField As Integer
        
        Private maxRecordIdinListField As Integer
        
        Private documentsField() As ResponseDocument
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property queryState() As Integer
            Get
                Return Me.queryStateField
            End Get
            Set
                Me.queryStateField = value
                Me.RaisePropertyChanged("queryState")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property stateExplanation() As String
            Get
                Return Me.stateExplanationField
            End Get
            Set
                Me.stateExplanationField = value
                Me.RaisePropertyChanged("stateExplanation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property documentsCount() As Integer
            Get
                Return Me.documentsCountField
            End Get
            Set
                Me.documentsCountField = value
                Me.RaisePropertyChanged("documentsCount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property maxRecordIdinList() As Integer
            Get
                Return Me.maxRecordIdinListField
            End Get
            Set
                Me.maxRecordIdinListField = value
                Me.RaisePropertyChanged("maxRecordIdinList")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("documents", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property documents() As ResponseDocument()
            Get
                Return Me.documentsField
            End Get
            Set
                Me.documentsField = value
                Me.RaisePropertyChanged("documents")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/")>  _
    Partial Public Class EntResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private documentUUIDField As String
        
        Private documentIDField As String
        
        Private codeField As String
        
        Private explanationField As String
        
        Private causeField As String
        
        Private contentField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property documentUUID() As String
            Get
                Return Me.documentUUIDField
            End Get
            Set
                Me.documentUUIDField = value
                Me.RaisePropertyChanged("documentUUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property documentID() As String
            Get
                Return Me.documentIDField
            End Get
            Set
                Me.documentIDField = value
                Me.RaisePropertyChanged("documentID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
                Me.RaisePropertyChanged("code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property explanation() As String
            Get
                Return Me.explanationField
            End Get
            Set
                Me.explanationField = value
                Me.RaisePropertyChanged("explanation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property cause() As String
            Get
                Return Me.causeField
            End Get
            Set
                Me.causeField = value
                Me.RaisePropertyChanged("cause")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=5)>  _
        Public Property content() As Byte()
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
                Me.RaisePropertyChanged("content")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="loadInvoice", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class loadInvoiceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("invoiceXMLList", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public invoiceXMLList() As eArsivGelen.InputDocument
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal invoiceXMLList() As eArsivGelen.InputDocument)
            MyBase.New
            Me.invoiceXMLList = invoiceXMLList
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="loadInvoiceResponse", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class loadInvoiceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return]() As eArsivGelen.EntResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As eArsivGelen.EntResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="QueryInvoice", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class QueryInvoiceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public paramType As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public parameter As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public withXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal paramType As String, ByVal parameter As String, ByVal withXML As String)
            MyBase.New
            Me.paramType = paramType
            Me.parameter = parameter
            Me.withXML = withXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="QueryInvoiceResponse", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class QueryInvoiceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As eArsivGelen.DocumentQueryResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As eArsivGelen.DocumentQueryResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="QueryInvoicesWithDocumentDate", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class QueryInvoicesWithDocumentDateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public startDate As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public endDate As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public withXML As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public minRecordId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal startDate As String, ByVal endDate As String, ByVal withXML As String, ByVal minRecordId As String)
            MyBase.New
            Me.startDate = startDate
            Me.endDate = endDate
            Me.withXML = withXML
            Me.minRecordId = minRecordId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="QueryInvoicesWithDocumentDateResponse", WrapperNamespace:="http://eainvoiceloadingservice.entegrator.com/", IsWrapped:=true)>  _
    Partial Public Class QueryInvoicesWithDocumentDateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://eainvoiceloadingservice.entegrator.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As eArsivGelen.DocumentQueryResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As eArsivGelen.DocumentQueryResponse)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LoadInvoiceWSChannel
        Inherits eArsivGelen.LoadInvoiceWS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoadInvoiceWSClient
        Inherits System.ServiceModel.ClientBase(Of eArsivGelen.LoadInvoiceWS)
        Implements eArsivGelen.LoadInvoiceWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_loadInvoice(ByVal request As eArsivGelen.loadInvoiceRequest) As eArsivGelen.loadInvoiceResponse Implements eArsivGelen.LoadInvoiceWS.loadInvoice
            Return MyBase.Channel.loadInvoice(request)
        End Function
        
        Public Function loadInvoice(ByVal invoiceXMLList() As eArsivGelen.InputDocument) As eArsivGelen.EntResponse()
            Dim inValue As eArsivGelen.loadInvoiceRequest = New eArsivGelen.loadInvoiceRequest()
            inValue.invoiceXMLList = invoiceXMLList
            Dim retVal As eArsivGelen.loadInvoiceResponse = CType(Me,eArsivGelen.LoadInvoiceWS).loadInvoice(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_loadInvoiceAsync(ByVal request As eArsivGelen.loadInvoiceRequest) As System.Threading.Tasks.Task(Of eArsivGelen.loadInvoiceResponse) Implements eArsivGelen.LoadInvoiceWS.loadInvoiceAsync
            Return MyBase.Channel.loadInvoiceAsync(request)
        End Function
        
        Public Function loadInvoiceAsync(ByVal invoiceXMLList() As eArsivGelen.InputDocument) As System.Threading.Tasks.Task(Of eArsivGelen.loadInvoiceResponse)
            Dim inValue As eArsivGelen.loadInvoiceRequest = New eArsivGelen.loadInvoiceRequest()
            inValue.invoiceXMLList = invoiceXMLList
            Return CType(Me,eArsivGelen.LoadInvoiceWS).loadInvoiceAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_QueryInvoice(ByVal request As eArsivGelen.QueryInvoiceRequest) As eArsivGelen.QueryInvoiceResponse Implements eArsivGelen.LoadInvoiceWS.QueryInvoice
            Return MyBase.Channel.QueryInvoice(request)
        End Function
        
        Public Function QueryInvoice(ByVal paramType As String, ByVal parameter As String, ByVal withXML As String) As eArsivGelen.DocumentQueryResponse
            Dim inValue As eArsivGelen.QueryInvoiceRequest = New eArsivGelen.QueryInvoiceRequest()
            inValue.paramType = paramType
            inValue.parameter = parameter
            inValue.withXML = withXML
            Dim retVal As eArsivGelen.QueryInvoiceResponse = CType(Me,eArsivGelen.LoadInvoiceWS).QueryInvoice(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_QueryInvoiceAsync(ByVal request As eArsivGelen.QueryInvoiceRequest) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoiceResponse) Implements eArsivGelen.LoadInvoiceWS.QueryInvoiceAsync
            Return MyBase.Channel.QueryInvoiceAsync(request)
        End Function
        
        Public Function QueryInvoiceAsync(ByVal paramType As String, ByVal parameter As String, ByVal withXML As String) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoiceResponse)
            Dim inValue As eArsivGelen.QueryInvoiceRequest = New eArsivGelen.QueryInvoiceRequest()
            inValue.paramType = paramType
            inValue.parameter = parameter
            inValue.withXML = withXML
            Return CType(Me,eArsivGelen.LoadInvoiceWS).QueryInvoiceAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_QueryInvoicesWithDocumentDate(ByVal request As eArsivGelen.QueryInvoicesWithDocumentDateRequest) As eArsivGelen.QueryInvoicesWithDocumentDateResponse Implements eArsivGelen.LoadInvoiceWS.QueryInvoicesWithDocumentDate
            Return MyBase.Channel.QueryInvoicesWithDocumentDate(request)
        End Function
        
        Public Function QueryInvoicesWithDocumentDate(ByVal startDate As String, ByVal endDate As String, ByVal withXML As String, ByVal minRecordId As String) As eArsivGelen.DocumentQueryResponse
            Dim inValue As eArsivGelen.QueryInvoicesWithDocumentDateRequest = New eArsivGelen.QueryInvoicesWithDocumentDateRequest()
            inValue.startDate = startDate
            inValue.endDate = endDate
            inValue.withXML = withXML
            inValue.minRecordId = minRecordId
            Dim retVal As eArsivGelen.QueryInvoicesWithDocumentDateResponse = CType(Me,eArsivGelen.LoadInvoiceWS).QueryInvoicesWithDocumentDate(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function eArsivGelen_LoadInvoiceWS_QueryInvoicesWithDocumentDateAsync(ByVal request As eArsivGelen.QueryInvoicesWithDocumentDateRequest) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoicesWithDocumentDateResponse) Implements eArsivGelen.LoadInvoiceWS.QueryInvoicesWithDocumentDateAsync
            Return MyBase.Channel.QueryInvoicesWithDocumentDateAsync(request)
        End Function
        
        Public Function QueryInvoicesWithDocumentDateAsync(ByVal startDate As String, ByVal endDate As String, ByVal withXML As String, ByVal minRecordId As String) As System.Threading.Tasks.Task(Of eArsivGelen.QueryInvoicesWithDocumentDateResponse)
            Dim inValue As eArsivGelen.QueryInvoicesWithDocumentDateRequest = New eArsivGelen.QueryInvoicesWithDocumentDateRequest()
            inValue.startDate = startDate
            inValue.endDate = endDate
            inValue.withXML = withXML
            inValue.minRecordId = minRecordId
            Return CType(Me,eArsivGelen.LoadInvoiceWS).QueryInvoicesWithDocumentDateAsync(inValue)
        End Function
    End Class
End Namespace
